var level1 = { "height":12,
 "layers":[
        {
         "compression":"zlib",
         "data":"eJxjYBgFo2D4AAAC0AAB",
         "encoding":"base64",
         "height":12,
         "name":"Background",
         "opacity":1,
         "type":"tilelayer",
         "visible":true,
         "width":15,
         "x":0,
         "y":0
        }, 
        {
         "compression":"zlib",
         "data":"eJxjZGBgYCQTjwIIYAZiFiBmHWiH4AFDwY0wQG56BGEASjwANw==",
         "encoding":"base64",
         "height":12,
         "name":"Plaform",
         "opacity":1,
         "type":"tilelayer",
         "visible":true,
         "width":15,
         "x":0,
         "y":0
        }, 
        {
         "compression":"zlib",
         "data":"eJxjYBgFo4AywA\/EAmTqlQViOSC2opJbADXMAJU=",
         "encoding":"base64",
         "height":12,
         "name":"Damage Walls",
         "opacity":1,
         "type":"tilelayer",
         "visible":true,
         "width":15,
         "x":0,
         "y":0
        }, 
        {
         "compression":"zlib",
         "data":"eJxjYBgFo2D4AAAC0AAB",
         "encoding":"base64",
         "height":12,
         "name":"Enemies",
         "opacity":1,
         "type":"tilelayer",
         "visible":true,
         "width":15,
         "x":0,
         "y":0
        }, 
        {
         "compression":"zlib",
         "data":"eJxjYBgFo2D4AAAC0AAB",
         "encoding":"base64",
         "height":12,
         "name":"Trigers",
         "opacity":1,
         "type":"tilelayer",
         "visible":true,
         "width":15,
         "x":0,
         "y":0
        }],
 "nextobjectid":1,
 "orientation":"orthogonal",
 "properties":
    {

    },
 "renderorder":"right-down",
 "tileheight":32,
 "tilesets":[
        {
         "firstgid":1,
         "image":"Tileset 1.png",
         "imageheight":960,
         "imagewidth":448,
         "margin":0,
         "name":"Tileset 1",
         "properties":
            {

            },
         "spacing":0,
         "tilecount":420,
         "tileheight":32,
         "tilewidth":32,
         "transparentcolor":"#ffffff"
        }],
 "tilewidth":32,
 "version":1,
 "width":15
};